version: "3"

#  sysctl -w vm.max_map_count=262144
#  sysctl -w fs.file-max=65536
#  ulimit -n 65536
#  ulimit -u 4096

services:
  sonarqube:
    image: sonarqube:7.4-community
    container_name: sonarqube
    ports:
      - 9000:9000
#    networks:
#      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://dbsonar/sonar
     # - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - sonarqube_data:/opt/sonarqube
  dbsonar:
    image: postgres:12.0
    container_name: sonarqube-pg
    hostname: sonarqube-pg
#    networks:
#      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql

#  scanner:
#    image: sonarsource/sonar-scanner-cli
#    container_name: scanner
#    networks:
#      - sonarnet
#    environment:
#      - SONAR_LOGIN=admin
#      - SONAR_PASSWORD=admin
#      - SONAR_HOST_URL=sonarqube:9000
#    volumes:
#      - ./:/usr/src

volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local

#networks:
#  sonarnet: